# Generated by Django 4.1.7 on 2023-10-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=255)),
                ('actual', models.FloatField()),
                ('previous', models.FloatField()),
                ('highest', models.FloatField()),
                ('lowest', models.FloatField()),
                ('dates', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
            ],
        ),
    ]
